### ISSUE TITLE
Improve support for error correlations etc.

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#140]
It was requested by [Andy Buckley](https://conference.ippp.dur.ac.uk/event/651/contributions/3587/attachments/3042/3307/buckley-hepdatabsm.pdf) in the [2017 HEPData advisory board meeting](http://conference.ippp.dur.ac.uk/e/HEPData2017) to provide better support for correlation information, both within a given analysis (HEPData record) and between different analyses.

**Credit:** thanks to Peter Skands for a useful discussion today about these issues.

# Correlations between analyses

Correlation information in a [YAML](http://yaml.org/) format might be specified something like:
```yaml
correlations:
- experiment: ATLAS
  name: luminosity in 2018
  level: fully-correlated
  tables:
  - doi: 10.17182/hepdata.12345.v1/t1
    label: lumi
  - doi: 10.17182/hepdata.12345.v1/t2
    label: lumi
  - doi: 10.17182/hepdata.56789.v1/t5
    label: luminosity
  - doi: 10.17182/hepdata.56789.v1/t6
    label: luminosity
  - doi: 10.17182/hepdata.56789.v2/t5
    label: luminosity
  - doi: 10.17182/hepdata.56789.v2/t6
    label: luminosity
- experiment: ATLAS
  name: luminosity in 2017
  level: fully-correlated
  tables:
  - {doi: 10.17182/hepdata.54321.v1/t1, label: lumi.}
  - {doi: 10.17182/hepdata.54321.v1/t2, label: lumi.}
```
This information could be provided in the first YAML document of a `submission.yaml` file included with a relevant data submission.  Or it could be maintained in a YAML file hosted by each of the experiments and harvested periodically (for example, once per day), similar to the ingestion of the [JSON file](http://rivet.hepforge.org/analyses.json) maintained by the Rivet authors containing a list of Rivet analyses.

Probably a new table of the (PostgreSQL) database would be needed to store this correlation information.  Then a link should appear next to each rendered table that returns relevant information on the correlations (if it exists) in both HTML and JSON formats.

# Linking error matrices to measurements

[Correlation/covariance matrices](https://github.com/HEPData/hepdata-submission#correlationcovariance-matrices) are often given as separate HEPData tables to the main measurement in a format with two independent variables (giving the bins) and one dependent variable (giving the covariance/correlation).  It would be useful to tie the measurement and the error matrix together, for example, by adding a key to the `submission.yaml` file like:
```yaml
related_to_table_doi: 10.17182/hepdata.34567.v1/t1
```
then links would be made from one table to the other.

# Including theoretical predictions in tables

Theoretical predictions are often included in the same tables as the data, e.g. see a recent [ATLAS example](https://www.hepdata.net/record/80812?version=3) giving Standard Model background expectations and signal predictions in a search for high-mass resonances.  The YAML representation for Table 1 is:
```yaml
dependent_variables:
- qualifiers:
  - {name: Process, value: Data}
  ...
- qualifiers:
  - {name: Process, value: SM}
  ...
- qualifiers:
  - {name: Process, value: '$W\to\tau\nu$'}
  ...
- qualifiers:
  - {name: Process, value: 'Jet'}
  ...
- qualifiers:
  - {name: Process, value: 'Others'}
  ...
- qualifiers:
  - {name: Process, value: '$W^{\prime}_{\rm SSM}$ (3 TeV)'}
  ...
- qualifiers:
  - {name: Process, value: '$W^{\prime}_{\rm NU}$ (3 TeV)'}
  ...
```
It would be useful to standardise the `name` and `value` of the distinguishing qualifiers to allow more automatic parsing.
