### ISSUE TITLE
submission: automatically identify "pyhf" file_type of resource files

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#163]
Consider the [pyhf](https://diana-hep.org/pyhf/) JSON files attached to https://www.hepdata.net/record/ins1748602?version=1 as an additional resource:
```yaml
additional_resources:
- description: Archive of full likelihoods in the HistFactory JSON format described
    in ATL-PHYS-PUB-2019-029 Provided are 3 statiscal models labeled RegionA RegionB
    and RegionC respectively each in their own sub-directory. For each model the background-only
    model is found i the file named 'BkgOnly.json' For each model a set of patches
    for various signal points is provided
  location: HEPData_workspaces.tar.gz
```
It would be good if we could automatically identify `pyhf` tarballs from the `description` and `location` of the `additional_resources` in the `submission.yaml` file, then we can make these resource files more prominent (as we already do for links to [Rivet](https://rivet.hepforge.org/) analyses).  Can we agree on some convention, e.g. a `location` ending in `workspaces.tar.gz`, that will be used for future `pyhf` uploads to HEPData?  The code can then check for this convention to write `file_type` as `pyhf` in the `dataresource` table of the database.

Cc: @lukasheinrich

**Comment by GraemeWatt** [comment]
More HEPData records have appeared with attached `pyhf` tarballs.

1.  https://www.hepdata.net/record/ins1765529?version=1
```yaml
additional_resources:
- description: Archive of full likelihoods in the HistFactory JSON format described
    in ATL-PHYS-PUB-2019-029. In the sub-directory the statiscal models SR-lowMass,
    SR-highMass and SR-combined are provided. The SR-combined is a combined fit of
    the SR-lowMass and SR-highMass. For each model the background-only model is found
    in the file named 'BkgOnly.json'. For each model a set of patches for various
    signal points is provided
  location: SUSY-2018-04_likelihoods.tar.gz
```
2.  https://www.hepdata.net/record/ins1771533?version=1
```yaml
additional_resources:
- description: Archive of full likelihoods in the HistFactory JSON format described
     in SUSY-2018-06. The background-only fit is found
     in the file named 'BkgOnly.json'. For each model a set of patches for various signal points is
     provided
  location: likelihoods_ANA-SUSY-2018-06_3L-RJ-mimic.tar.gz
```
The proposed convention of a `location` ending in `workspaces.tar.gz` has clearly not been followed.  Maybe we need to instead look for a string like `HistFactory JSON` contained in the `description`?

**Comment by GraemeWatt** [comment]
Agreement with Louie Corpe for HEPData recommendations for ATLAS:
```python
if location.endswith('.tar.gz') and \
   ('histfactory json' in description.lower() or 'pyhf' in description.lower()):
    file_type = 'pyhf_tarball'
```
whereas individual pyhf JSON files (#164) would have:
```python
file_type = 'pyhf_json'
```
For individual pyhf JSON files when we provide native support, we would probably identify them by requiring a `data_schema` key rather than using the `location` or `description`.

**Comment by kratsg** [comment]
Can we add an option that allows you to override the automated detection? E.G. something like

```
additional_resources:
- description: Archive of full likelihoods in the HistFactory JSON format described
     in SUSY-2018-06. The background-only fit is found
     in the file named 'BkgOnly.json'. For each model a set of patches for various signal points is
     provided
  location: likelihoods_ANA-SUSY-2018-06_3L-RJ-mimic.tar.gz
  type: histfactory
```

**Comment by GraemeWatt** [comment]
Hopefully, we'll get around to tackling this issue soon.  But I noticed that the [latest HEPData record](https://www.hepdata.net/record/ins1831992) (released today) with an attached pyhf archive has:
```yaml
additional_resources:
- description: Archive of full statistical likelihoods and README
  location: FullLikelihoods_sm.tar.gz
```
@ldcorpe, is the [agreement above](https://github.com/HEPData/hepdata/issues/163#issuecomment-601321478) not being followed by ATLAS?  Should we add "likelihoods" as an additional trigger phrase in addition to "histfactory json" or "pyhf"?

@kratsg, yes, we should probably allow something like `type: pyhf_tarball` (better than `type: histfactory`) to override an automatic detection of the file type based on trigger phrases.  We'd need to first modify the JSON schema that defines the `submission.yaml` file (see HEPData/hepdata-validator#23) to add the `type` field.  Of course, future ATLAS submissions would then need to consistently specify `type: pyhf_tarball` in the `submission.yaml` file.
