### ISSUE TITLE
records: display default CC0 license

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#792]
When addressing issue #740 via PR #745, we decided not to display the default [CC0](https://creativecommons.org/publicdomain/zero/1.0/) license to avoid unnecessary clutter.  However, at the [Invisibles Data Days](https://indico.ph.tum.de/event/7592/) last week in Munich, @lukasheinrich pointed out that the default license information (under [Terms of Use](https://www.hepdata.net/terms)) is not easy to find, so we should make it more prominent.  If a license for a data table or an additional resource is not given explicitly, we should display the [CC0](https://creativecommons.org/publicdomain/zero/1.0/) license, i.e.
```yaml
name: CC0
url: https://creativecommons.org/publicdomain/zero/1.0/
description: CC0 enables reusers to distribute, remix, adapt, and build upon the material in any medium or format, with no conditions.
```

Another issue is that historically some submissions converted from the `oldhepdata` format wrote null values for the `name`, `url` and `description` before an issue HEPData/hepdata-converter#32 was addressed in the converter software.  Example records are https://www.hepdata.net/record/95927?version=1 and https://www.hepdata.net/record/89321?version=1 .  The CC0 license should be displayed for these cases.
