### ISSUE TITLE
Error message: None is not of type u'array' in None

### ISSUE THREAD

**Issue by nlurkin** [HEPData/hepdata#87]
Hello,

I am not able to upload data on the website. I receive the error message: "None is not of type u'array' in None". What does this error mean? How can I fix my yaml?
As far as the format is concerned, I think I am using the same as given in the examples (though it is difficult to know exactly as there is no list/description of allowed keywords).

Regards,
Nicolas

File is (kept only one point):
```
independent_variables:
- header: {name: x}
  values:
  - {low: 0.0102854, high: 0.0102854}
dependent_variables:
- header: {name: "Data events"}
  values:
  - value: 22284 
    errors: 
    - {symerror: 149.278, label: 'stat'} 

- header: {name: "MC events(a=0)"}
  values:
  - value: 156443
    errors: 
  - {symerror: 414.514, label: 'stat'}
```

**Comment by eamonnmag** [comment]
Hi @nlurkin, the problem is with the indentation here

```
  errors: 
- {symerror: 414.514, label: 'stat'}
```
 On the last line. You need to have it indented, otherwise 'errors' will be null. To debug, sometimes it's better to check the conversion to json on https://www.json2yaml.com/ if in doubt, that way you'll see if something doesn't look right. Apologies for the error message, we get them directly from the parser, so it's possible they are obscure sometimes.

```
independent_variables:
- header: {name: x}
  values:
  - {low: 0.0102854, high: 0.0102854}
dependent_variables:
- header: {name: "Data events"}
  values:
  - value: 22284 
    errors: 
    - {symerror: 149.278, label: 'stat'} 

- header: {name: "MC events(a=0)"}
  values:
  - value: 156443
    errors: 
    - {symerror: 414.514, label: 'stat'}
```
